version: 2.1

executors:
  default:
    machine: true
    environment:
      DOCKER_IMAGE_WEB: r.chiya.dev/genshin-web
      DOCKER_IMAGE_SYNC: r.chiya.dev/genshin-sync
      UMAMI_URL: https://a.chiya.dev/57a842aa-1d89-4c48-aaea-2b9b98b4e818

jobs:
  deploy-web:
    executor: default
    steps:
      - checkout
      - run: docker build -t $DOCKER_IMAGE_WEB -f Dockerfile.web --build-arg UMAMI_URL .
      - run: echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY -u "$DOCKER_USERNAME" --password-stdin
      - run: docker push $DOCKER_IMAGE_WEB

  deploy-sync:
    executor: default
    steps:
      - checkout
      - run: docker build -t $DOCKER_IMAGE_SYNC -f Dockerfile.sync .
      - run: echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY -u "$DOCKER_USERNAME" --password-stdin
      - run: docker push $DOCKER_IMAGE_SYNC

workflows:
  version: 2
  default:
    jobs:
      - deploy-web:
          context:
            - do-registry

      - deploy-sync:
          context:
            - do-registry
